/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizzesNewRouteImport } from './routes/quizzes.new'
import { Route as PlayGameIdRouteImport } from './routes/play.$gameId'
import { Route as HostGameIdRouteImport } from './routes/host.$gameId'
import { Route as QuizzesQuizIdEditRouteImport } from './routes/quizzes.$quizId.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesNewRoute = QuizzesNewRouteImport.update({
  id: '/quizzes/new',
  path: '/quizzes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayGameIdRoute = PlayGameIdRouteImport.update({
  id: '/play/$gameId',
  path: '/play/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const HostGameIdRoute = HostGameIdRouteImport.update({
  id: '/host/$gameId',
  path: '/host/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesQuizIdEditRoute = QuizzesQuizIdEditRouteImport.update({
  id: '/quizzes/$quizId/edit',
  path: '/quizzes/$quizId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/host/$gameId': typeof HostGameIdRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/quizzes/new': typeof QuizzesNewRoute
  '/quizzes/$quizId/edit': typeof QuizzesQuizIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/host/$gameId': typeof HostGameIdRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/quizzes/new': typeof QuizzesNewRoute
  '/quizzes/$quizId/edit': typeof QuizzesQuizIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/host/$gameId': typeof HostGameIdRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/quizzes/new': typeof QuizzesNewRoute
  '/quizzes/$quizId/edit': typeof QuizzesQuizIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/join'
    | '/login'
    | '/register'
    | '/host/$gameId'
    | '/play/$gameId'
    | '/quizzes/new'
    | '/quizzes/$quizId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/join'
    | '/login'
    | '/register'
    | '/host/$gameId'
    | '/play/$gameId'
    | '/quizzes/new'
    | '/quizzes/$quizId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/join'
    | '/login'
    | '/register'
    | '/host/$gameId'
    | '/play/$gameId'
    | '/quizzes/new'
    | '/quizzes/$quizId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  HostGameIdRoute: typeof HostGameIdRoute
  PlayGameIdRoute: typeof PlayGameIdRoute
  QuizzesNewRoute: typeof QuizzesNewRoute
  QuizzesQuizIdEditRoute: typeof QuizzesQuizIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/new': {
      id: '/quizzes/new'
      path: '/quizzes/new'
      fullPath: '/quizzes/new'
      preLoaderRoute: typeof QuizzesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$gameId': {
      id: '/play/$gameId'
      path: '/play/$gameId'
      fullPath: '/play/$gameId'
      preLoaderRoute: typeof PlayGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$gameId': {
      id: '/host/$gameId'
      path: '/host/$gameId'
      fullPath: '/host/$gameId'
      preLoaderRoute: typeof HostGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$quizId/edit': {
      id: '/quizzes/$quizId/edit'
      path: '/quizzes/$quizId/edit'
      fullPath: '/quizzes/$quizId/edit'
      preLoaderRoute: typeof QuizzesQuizIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  HostGameIdRoute: HostGameIdRoute,
  PlayGameIdRoute: PlayGameIdRoute,
  QuizzesNewRoute: QuizzesNewRoute,
  QuizzesQuizIdEditRoute: QuizzesQuizIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
